### PR TITLE
images support via gosseract

### PR DESCRIPTION
**Pull request by avelino**
issue #14

### CODE REVIEW

**Comment by dhowden** [comment]
This adds tesseract as a build-time dependency which breaks builds for all existing users, and hence can't be merged as-is.

    $ go get ./...
    # github.com/otiai10/gosseract/tesseract
    ../../otiai10/gosseract/tesseract/tess.cpp:1:10: fatal error: 'tesseract/baseapi.h' file not found

I think that adding build tags around the gosseract-specific calls would be the simplest way to fix this (as mentioned in #14).  We would then have a build tag `ocr` which would switch on the gosseract code (and then require tesseract).

**Comment by avelino** [comment]
```
$ go get github.com/poorny/docconv
$ echo $GOPATH
$ cd ~/.gocode/src/github.com/poorny/docconv/docconv
$ echo "lero lero" >> teste.txt
$ go run main.go -input=teste.txt
lero lero
$ go run main.go -input=parateste.png
```

Just give error when someone is image processing. This implementation does not break the software for those who don't use image processing

**Comment by lerrua** [comment]
+1

**Comment by dhowden** [comment]
That's not using your branch with the goseeract stuff in (`go get` checks out the master branch of your fork).  This is what I get when I use your branch:

```
docconv/ (poorny-gosseract_support!) $ pwd
$GOPATH/src/github.com/sajari/docconv/docconv
docconv/ (poorny-gosseract_support!) $ go build
# github.com/otiai10/gosseract/tesseract
../../../otiai10/gosseract/tesseract/tess.cpp:1:10: fatal error: 'tesseract/baseapi.h' file not found
```

**Comment by avelino** [comment]
How can we make this implementation to not break the docconv?

**Comment by dhowden** [comment]
You need to use a build tag to isolate the gosseract calls so that they are only included when you include the build tag in go commands. 

I can do this for you if you want, though I can't look at it for a few days.

**Pull request merged**
