### PR TITLE
Extract image-based PDFs

### PR DESCRIPTION
**Pull request by Southclaws**
I quickly knocked this up then realised #19 already exists! But oh well, it's done now so it might be worth looking at...

It's not really solid code yet (error handling is literally just printf - but there doesn't seem to be a more elegant method available in the codebase either) but I thought I'd open a PR anyway to get some feedback :)

### CODE REVIEW

**Comment by mish15** [comment]
@Southclaws thanks for the PR. This lib was written a while back, error handling could definitely be much better! :) #19 got so close to getting this right, we should likely try to finish that off as it covers more image types and seems a bit closer to complete. Did you try that branch out at all?

**Comment by Southclaws** [comment]
I didn't get a chance to try out 19 yet, I wrote this quickly before finding that PR! I'll give it a try later today and maybe help contribute to that solution :)

**Comment by mish15** [comment]
Sounds good! Keep us posted, would be great to close that out
-- 
*Hamish Ogilvy*
Sajari Pty Ltd
L3, 1 Buckingham St, Surry Hills NSW 2010, Australia
m: +61 414 658 353 | *e: *hogilvy@sajari.com
*w:* www.sajari.com | @hamishogilvy
<https://www.twitter.com/hamishogilvy>

**Comment by mish15** [comment]
Closing in favour of #40

**Pull request closed without merging**
