### PR TITLE
fix ConvertRTF ignoring short lines

### PR DESCRIPTION
**Pull request by remLse**
fix issue #90

### CODE REVIEW

**Comment by jonathaningram** [comment]
@remLse do you want to have a go at adding a test for this? I know we don't have it set up for you to easily add a test, but see how you go.

Also, I think the `len(line) > 4` was just protecting against index out of bounds errors, not that it actually tried to online include lines at least 5 characters. Do you agree that was the intention from reading the code?

**Comment by jonathaningram** [comment]
@remLse it's now the weekend, so likely won't get back to this until next week.

**Comment by remLse** [comment]
> Also, I think the `len(line) > 4` was just protecting against index out of bounds errors, not that it actually tried to online include lines at least 5 characters. Do you agree that was the intention from reading the code?

Yes, I agree with this.

I will try adding a test!

There's no need to hurry, I can work with my local changes for now. Thanks for taking a look!

**Comment by remLse** [comment]
While I'm at it, do you think it would be good to remove the first line (just dashes from UnRTF) from the output?

**Comment by remLse** [comment]
I’ve prepared another commit with two changes to the output of ConvertRTF. Let me know if you’d like it to be included in this pull request. Feel free to merge if you are satisfied with the tests, but don’t want the changes to the output to be included.

The relevant commit is on a branch of my fork: https://github.com/remLse/docconv/commit/cd7355931e38b97426629f91b99f425872020a50

### change 1: remove dashed line from output

before:
```
-----------------
hello world
helo

1
```

after:
```
hello world
helo

1
```

### change 2: remove comment prefix “### “ from metadata

before:
```
### creation date: 29 March 2021 11:30
### revision date: 9 April 2021 16:36
### last printed: 
CreatedDate: 1617017400
```

after:
```
creation date: 29 March 2021 11:30
revision date: 9 April 2021 16:36
last printed: 
CreatedDate: 1617017400
```

**Review by jonathaningram — APPROVED** [review]

**Pull request merged**
