### PR TITLE
doc.go: return before channel response

### PR DESCRIPTION
**Pull request by pixge**
Returning a value to channels before return command.

### CODE REVIEW

**Comment by albertosouza** [comment]
I'm having same problem with some docs and ends in a DeadLock.

```
2023/07/19 19:45:16 ConvertDoc: could not read doc: mscfb: bad signature; 3832054403461042213
2023/07/19 19:45:16 wvText: exit status 255
```

**Comment by albertosouza** [comment]
Tested and that changes works

**Comment by turtleDev** [comment]
+1. Running into this problem often.

**Review by jonathaningram — APPROVED** [review]

**Comment by jonathaningram** [comment]
@pixge thanks for the contribution and thanks for your patience :)

**Pull request merged**
